site_name: 研究所畢業資訊 FAQ
site_description: 研究所畢業相關資訊與常見問題整理

theme:
  name: material
  language: zh-TW

  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 首頁: index.md
  - 常用網址:
      - links/index.md
      - 訂購網站: https://docs.google.com/forms/d/e/1FAIpQLSfigaZEGt4SE57JOXiF9-oLusy4qgXGmEVtma_jCFoO7RRFgg/viewform
      - 碩士服明細: https://sites.google.com/colorweb.com.tw/ntust/%E9%A6%96%E9%A0%81?pli=1&authuser=0
      - 拍照預約表單: https://docs.google.com/forms/d/e/1FAIpQLSfx-lppzU3pMrn4D2LoDwOpp26mzeMRSfp7pNJM2-Dw5tb6Dg/viewform
      - 學位服提問區: https://docs.google.com/spreadsheets/d/12cQSMlPNDS9QlquOWXorjFyWQR4VXqwr6aHcYo5aRr8/edit?gid=0#gid=0

extra_javascript:
  - javascripts/external-links.js
