site_name: 研究所畢業資訊 FAQ
site_description: 研究所畢業相關資訊與常見問題整理

theme:
  name: material
  language: zh-TW

  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 首頁: index.md
  - 常用網址:
      - links/index.md
      - 學位服訂購_碩士:(https://forms.gle/YZNvFx9otz4wtPqs5)

extra_javascript:
  - javascripts/external-links.js
